### ISSUE TITLE
未选中舰仍然提醒

### ISSUE THREAD

**Issue by Lanyangzhi** [SoraYama/poi-plugin-lock-reminder#1]
在自定义模式-选中舰"不被提醒"下选择需要的舰娘 再切换到"被提醒" 产生了没有被选择的舰娘仍然提醒的bug
(被选中的舰娘是否提醒不明)

[![7-EMMH-O6-IG9-U9-H-RQ-LJ-V.png](https://i.postimg.cc/766rys2q/7-EMMH-O6-IG9-U9-H-RQ-LJ-V.png)](https://postimg.cc/3yPcXZ1q)

**Comment by SoraYama** [comment]
感谢反馈 想问下丛云在提醒前舰队里有吗？

**Comment by Lanyangzhi** [comment]
> 感谢反馈 想问下丛云在提醒前舰队里有吗？

图鉴里有 舰队里没有(已拆)

**Comment by SoraYama** [comment]
在想一种可能，是不是在掉落的时候你的模式是不被提醒，然后在后续战斗到回港这段时间切到了被提醒的模式下呢？

**Comment by Lanyangzhi** [comment]
> 在想一种可能，是不是在掉落的时候你的模式是不被提醒，然后在后续战斗到回港这段时间切到了被提醒的模式下呢？

...并不是 我配置好就没有碰过了

**Comment by Lanyangzhi** [comment]
@SoraYama Saddd
[![QQ-20190127002831.png](https://i.postimg.cc/BvjC7L0M/QQ-20190127002831.png)](https://postimg.cc/XZ0FpvXC)

**Comment by SoraYama** [comment]
麻烦点击左下角 开发者工具 然后在 console 选项卡中输入 `getStore('config.plugin.poi-plugin-lock-reminder')` 然后点击结果每一项左边的小三角截个图吧

**Comment by Lanyangzhi** [comment]
每一项吗？会不会太多了点...

**Comment by SoraYama** [comment]
明白了，我一会儿发个新版本再麻烦你试试好了

**Comment by SoraYama** [comment]
@Lanyangzhi 检查更新下再试试呢

**Comment by Lanyangzhi** [comment]
似乎可以正常使用了 交了一个海防任务测试功能
大半夜还要修bug真是麻烦你了
![8r3spgyjfq av jq 5f y0i](https://user-images.githubusercontent.com/10362972/51790893-08734200-21d6-11e9-99a4-4767b5dce6ff.png)

**Comment by SoraYama** [comment]
没关系 任务获取刚好没测过真是感谢汇报了
