### ISSUE TITLE
宗谷並未加入提醒

### ISSUE THREAD

**Issue by darkwang2003** [SoraYama/poi-plugin-lock-reminder#2]
目前觀察宗谷可能因為分類的關係，並未歸類到現有艦隊內。
是否要加入新的類別呢?

**Comment by SoraYama** [comment]
@darkwang2003 感谢回报，最近实在没空看，大概要等到9月份了。如果有PR的话非常欢迎。

**Comment by darkwang2003** [comment]
率苦了，有時間再處理就好。

**Comment by SoraYama** [comment]
可以升级到 1.0.6-beta.0 试一下

**Comment by darkwang2003** [comment]
變成不會自己吃現有艦娘的情況了，就算把所有的艦娘都打勾也沒用。
之前暫時沒有的艦娘數是1，現在變成264。

**Comment by SoraYama** [comment]
@darkwang2003 修复了下，升级到 beta.1 试试

**Comment by darkwang2003** [comment]
感覺應該沒問題了，辛苦您了。

**Comment by SoraYama** [comment]
OK，感谢回报
